### PR TITLE
Add a tooltip explaining the Critical Mode option

### PR DESCRIPTION
**Pull request by Heufneutje**
This was requested in the #help channel on the randomizer Discord.

### CODE REVIEW

**Comment by Heufneutje** [comment]
Any chance of this getting merged?

**Comment by afresquet** [comment]
I am doing major changes to this repository and it will no longer include the React app.

I will be coming back to the pending pull requests in the future once I have stable interactions between the different repositories of the project.

**Comment by afresquet** [comment]
Actually, please do this PR on the frontend repository, and please merge into develop, never master. I will accept it over there. https://github.com/afresquet/kh2fm-randomizer-frontend

**Comment by Heufneutje** [comment]
Will do.

**Comment by Nicholas-Steel** [comment]
And they did https://github.com/afresquet/kh2fm-randomizer-frontend/pull/2

**Pull request closed without merging**
