### PR TITLE
Boss improvements/logic

### PR DESCRIPTION
**Pull request by snelson3**
I know none of the current developers have boss randomizing as a high priority, so I decided to step into the ring and start working on it.

This pull request adds the following features to boss rando

* placement logic: bosses can have a "bannedFrom" attribute listing places where they don't work. Then the randomizer will use that information to randomize bosses among locations they are allowed to be in. This should be fairly easy to extend when these rules need to be more complex
* patches: Some bosses would work with just a simple patch, so when the codes for each replacement are created, if there is a code to apply it is added to the joker for that location (currently the only code is "Roxas can RC" for any fight that replaces Axel II)
* useWhenReplacing: Some bosses appear in the game multiple times, but only one of those versions is beatable (IE Hades), so this value is used to make it spawn the beatable version instead of the unbeatable version.

In terms of actual changes to enemies, I went through the boss bug reports channel and collated all the reports I thought were worth a location ban (mostly just reports of hard crashes, drive/mickey tposes seem mostly useless to try and fix through individual bans), and added that information to the json records. I also uncommented Hades and Xigbar fights (Xigbar works well in most places I've tried).

### CODE REVIEW

**Comment by snelson3** [comment]
I've made a couple more improvements since the initial pull request
* The Mushrooms page was missing a world/room/event code, so the jokers were messed up with enemy rando turned on (causing many random crashes)
* Added one instance of Hercules/Leon/Yuffie/Tifa/Cloud to the pool each. Unsure if it's better to add each copy of them to the pool individually (would make these bosses more common than others), or to randomize each instance of them as one (so if Terra replaces Yuffie than there are 4 instances of Terra put in the cups). Also added the "01" to the start of each FF7 characters value, because when I tested putting them in Roxas room I noticed they normally had about half a health bar, but if you added the "01" it seemed to be a more normal amount of health. 
* Added a couple more instances of specific replacement bans, based on recent reports in the boss bug room (as well as a comment for each ban explaining why)

**Comment by snelson3** [comment]
Found out why you can't move in Marluxias room with a different boss, and pushed a fix for it (that rooms MSN file has 1 extra line that calls a function, and nulling out that function call fixes it).

Also commented out the fight on day 3 of STT where you fight the dusk with the struggle bat, as it can softlock with other enemies if you kill it before the fight is over (would be an easy fix, just give it max HP/invulnerable but not important).

**Comment by snelson3** [comment]
Made some major improvements to the enemy randomizer, and it now appears to be at least 90% stable (at the very least, it's way more stable than the boss randomizer). The changes I made:

- Added toggle for enemy randomizer to experimental page
- Add path to set all enemies spawn limiter to 4 (this was the thing causing a lot of fights to not spawn all the enemies it needed to, preventing the fights from completing). Since enemies are 1-1 swapped it would probably be better for the enemies to swap spawn limiter values, but this was the quickest fix for now (I chose 4 because it is the lowest spawn limiter of any of the enemies [fiery globe], so it should enable all the spawns to happen in any fight).
- added eventGroup for mushrooms and disney castle escort I, as the event listing was (02,02,01) instead of just (02). This had to be done for the conditional to work
- Commented out the thresholder fight gargoyles from being randomized, as I noticed those enemies didn't seem to work.
- Commented out all the cavern/transport to rememberence fights. I was unable to get the conditionals for those fights working, so I took them out of the pool.
- Commented out the Ambush II fight. For some reason the fight doesn't end after all the enemies die (it's the only currently randomized fight where that is happening). Likely could be fixed with a change to the MSN for that fight.
- Commented out the Mushrooms from being in the randomization pool
- Commented out the Solar Sailor fight, in my testing the weight was filling up way to quickly and the fight was not possible to beat
- Commented out the Cylinder Lasers fight, as apparently the NOBODY_FROM_FINAL_BATTLE_V1 is the only enemy that can damage the lasers


Also the reason Vexen was crashing in so many boss fights was because he loaded Anti-Sora into memory, even though the absense of the Vexen MSN means Anti-Sora will never spawn. So I added a code for Vexen that prevents Anti-Sora from getting loaded into memory which makes him work in a lot more places (specifically he works in OC Pete II, which is a fight that famously crashes for most of the games bosses).

**Comment by snelson3** [comment]
Last improvement for this pull request:

I estimated a "size" for each boss and boss location (adding up the sizes of related files to each object and/or map). Then I did some testing and estimated a maxSize of boss that can be in each room before problems happen. The estimate is pretty rough still but should remove a lot of the crashes/tposes that happen currently (because it will prevent high memory bosses from going to high memory locations).

**Comment by afresquet** [comment]
I will merge this into a separate branch until I have time to review it, but I'll push it to live so it can get played with, thank you!

**Pull request merged**
